const ADD_CART_ITEM = "ADD_CART_ITEM";
const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
const CART_SHIPPING_ADDRESS = "CART_SHIPPING_ADDRESS";
const CART_PAYMENT_METHOD = "CART_PAYMENT_METHOD";

export {
  ADD_CART_ITEM,
  REMOVE_CART_ITEM,
  CART_SHIPPING_ADDRESS,
  CART_PAYMENT_METHOD,
};
